### ISSUE TITLE
An error occurred while running cordova plugin add cordova-plugin-pesdk

### ISSUE THREAD

**Issue by IonicBlog** [imgly/pesdk-ionic-demo#1]
$ ionic cordova plugin add --searchpath ../pesdk-cordova-demo cordova-plugin-pesdk
> cordova plugin add cordova-plugin-pesdk --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
        
[ERROR] An error occurred while running cordova plugin add cordova-plugin-pesdk
        --save (exit code 1):
        
        Error: Registry returned 404 for GET on
        https://registry.npmjs.org/cordova-plugin-pesdk

![image](https://user-images.githubusercontent.com/13251600/28060658-692eef7e-665a-11e7-86b1-29ba3999dd62.png)

**Comment by maltebaumann** [comment]
Hey,
you need to run `ionic plugin add --searchpath ../pesdk-cordova-demo cordova-plugin-pesdk`, not `ionic cordova plugin...`. Cordova seems to ignore the `--searchpath` argument.

**Comment by TongeJie** [comment]
Mac-mini:PESDKDemo xx$ ionic plugin add --searchpath ../pesdk-cordova-demo cordova-plugin-pesdk
The plugin command has been renamed. To find out more, run:

  ionic cordova plugin --help
Mac-mini:PESDKDemo xx$ ionic plugin add ../pesdk-cordova-demo cordova-plugin-pesdk
The plugin command has been renamed. To find out more, run:

  ionic cordova plugin --help

Mac-mini:PESDKDemo xx$ cordova plugin add ../pesdk-cordova-demo cordova-plugin-pesdk
Error: Invalid Plugin! ../pesdk-cordova-demo needs a valid package.json
![image](https://user-images.githubusercontent.com/13251600/28098866-52677608-66eb-11e7-843a-a9afa870e0d1.png)

**Comment by maltebaumann** [comment]
Hi, I just updated to Ionic 3.5 and Cordova 7.0.1 and it seems like Angular has changed some CLI interfaces and the Ionic CLI wrapper doesn't pass all arguments to Cordova. Could you try to install the plugin from `/pesdk-cordova-demo` using the following command:

```
$ cordova plugin add ../pesdk-cordova-demo --nofetch
```

This works for me, so I hope it fixes your issues. Thanks!

**Comment by n0490b** [comment]
@maltebaumann I'm using Ionic 3.5, Cordova 7.0.1 and Ionic CLI 3.12.0 and I tried everything in this thread but I'm still getting a 404s. Do you have any other solutions?

If I want to add pesdk to my ionic app without using the demo how do I do that? Are there any instructions on how to import the library? 

Thank you

**Comment by maltebaumann** [comment]
Hey @n0490b, 
can you share the exact error message? Haven't seen 404s before. In theory, you only need to add the iOS and Android platforms, link our Android and iOS SDKs according to the 'manual' steps detailed in our [iOS](https://docs.photoeditorsdk.com/guides/ios/v8/introduction/getting_started) and [Android](https://docs.photoeditorsdk.com/guides/android/v4/introduction/getting_started) docs. And then add a native Cordova/Ionic plugin that bridges between the native platforms and Ionic. You can take the plugin code from this repository and adjust it to your needs. For more details, check out the [blog post](https://blog.photoeditorsdk.com/photoeditor-sdk-cordova-dabe146e6c13) where I described the process in more detail.

Best,
Malte

**Comment by maltebaumann** [comment]
Sorry, I just saw the original 404 message at the top. You need to append the `--nofetch` option to ensure the local plugin from `../pesdk-cordova-demo` is used. Fetching the plugin from the npm registry won't work as it's not listed there.

**Comment by n0490b** [comment]
Hi @maltebaumann  it still doesn't work.
Ive tried both of these commands 
cordova plugin add ../pesdk-cordova-demo --nofetch

This is the exact error I'm getting

```
Error: Registry returned 404 for GET on https://registry.npmjs.org/PESDKDemo
```

Heres what I did 

1. `ionic start PESDKDemo blank`
2. `git init`
3. `cd pesdk`
4. `ionic cordova platform add android`
5. `ionic cordova platform add ios`
6. `git submodule add git@github.com:imgly/pesdk-cordova-demo.git`
7. `cordova plugin add ../pesdk-cordova-demo --nofetch`

All of this from the ionic `PESDKDemo` directory

**Comment by maltebaumann** [comment]
The `cd pesdk` command switches into the Ionic project, but `git submodule add git@github.com:imgly/pesdk-cordova-demo.git` and `cordova plugin add ../pesdk-cordova-demo --nofetch` must be called from the root directory (`PESDKDemo`) as the plugin is outside of the example project. You need to execute `cd ..` between steps 5 and 6. I'll update the `README` and sorry I didn't see this earlier.
